config/routes.rb
FiveInch::Application.routes.draw do
  get "discussions/create"

  get "discussions/update"

  get "discussions/show"

  get "discussions/destroy"

  root :to => 'welcome#index'

  resources :users 
  resources :projects do
    resources :discussions
  end

  resources :discussions do 
    resources :discussions_responses
  end
  resources :session, :only => [:create, :destroy, :new]
  resources :discussions_responses, :only => [:update]
  get 'login' => 'sessions#new'
  get 'signout' => 'sessions#destroy'
  get 'signup' => 'users#new'
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  attr_accessible :content, :title
  belongs_to :project
  belongs_to :user
  has_many :discussion_responses
  
  default_scope order('created_at DESC')
end

app/models/discussion_response.rb
class DiscussionResponse < ActiveRecord::Base
  attr_accessible :content, :discussion_id
  belongs_to :discussion
  belongs_to :user

  default_scope order('created_at DESC')
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :collaborators, :join_table => 'users_projects', :class_name => 'User'
  has_many :users_projects
  belongs_to :creator, :class_name => 'User'
  has_many :discussions

  default_scope order('updated_at DESC')
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :password
  has_and_belongs_to_many :projects, :join_table => 'users_projects'
  has_many :users_projects
  has_many :owned_projects, :class_name => 'Project'
  has_many :discussions
  has_many :discussion_responses
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include ApplicationHelper
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  def create
    p params
    project = Project.find(params[:project_id])
    @discussion = Discussion.new
    if @discussion.save
      project.discussions << @discussion
      current_user.discussions << @discussion
      render :partial => 'discussions/discussion_init'
    else
      # failure
    end
  end

  def new
    @discussion = Discussion.new
  end

  def update
    @discussion = Discussion.find(params[:id])
    @discussion.update_attributes(params[:discussion_data])
    render :partial => 'discussions/discussion_thumb', :locals => {:discussion => @discussion}
  end

  def show
    @discussion = Discussion.find(params[:id])
  end

  def destroy
  end
end

app/controllers/discussions_responses_controller.rb
class DiscussionsResponsesController < ApplicationController
  def create
    p params
    discussion = Discussion.find(params[:discussion_id])
    @discussion_response = DiscussionResponse.new
    if @discussion_response.save
      discussion.discussion_responses << @discussion_response
      current_user.discussion_responses << @discussion_response
      render :partial => 'discussions_responses/discussion_response_template'
    else
      # failure
    end
  end

  def update
    p 'params = '
    p params
    @discussion_response = DiscussionResponse.find(params[:id])
    @discussion_response.update_attributes(params[:discussion_response_data])
    p 'discussionresponse'
    p @discussion_response
    render :partial => 'discussions_responses/indi_show', :locals => {:response => @discussion_response}
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @project = Project.new
  end

  def create
    user = User.find(current_user)
    project = Project.new(params[:project])
    if project.save
      user.owned_projects << project
      redirect_to project_path(project)
    else
      redirect_to root_path
    end
  end

  def show
    @project = Project.find(params[:id])
    @discussions = @project.discussions
  end

  def update
    project = Project.find(params[:id])
    if project.update_attributes(params[:project_data])
      render json: {response: true}
    else
      render json: {response: false}
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by_email(:params[:email])
    if user.authenticate(:password)
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      redirect_to root_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(params[:user])
    if user.save
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      redirect_to new_user_path
    end
  end

  def show
    @user = current_user
    @owned_projects = @user.owned_projects
    @projects = @user.projects
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user
		User.find(session[:user_id]) if session[:user_id]
	end
end

app/views/discussions/_discussion_init.html.erb
<div class="indi-content-shell content-1 new_discussion_shell">
  <%= text_field_tag 'discussion[title]', @discussion.title, :class => 'discussion_title updatable_discussion_data plain input-bottom-border-1 block text-input-1', :data => {:discussion_id => @discussion.id}, :placeholder => 'Title', :autocomplete => 'off' %>
  <%= text_area_tag 'discussion[content]', @discussion.content, :class => 'discussion_content updatable_discussion_data plain block text-input-1', :data => {:discussion_id => @discussion.id}, :placeholder => 'Content' %>
  <%= button_tag 'Start New Discussion', :class => 'add_discussion-btn', :data => {:discussion_id => @discussion.id} %>
</div>

app/views/discussions/_discussion_thumb.html.erb
<%= link_to discussion_path(discussion), :class => 'pure-button discussion-thumb-shell' do %>
  <p class="discussion-thumb-title"><%= discussion.title %></p>
  <p class="discussion-thumb-content"><%= discussion.content %></p>
<% end %>

app/views/discussions/show.html.erb
<div class="indi-content-shell content-1 new_discussion_shell">
  <%= text_field_tag 'discussion[title]', @discussion.title, :class => 'discussion_title updatable_discussion_data plain input-bottom-border-1 block text-input-1', :data => {:discussion_id => @discussion.id}, :placeholder => 'Title', :autocomplete => 'off' %>
  <%= text_area_tag 'discussion[content]', @discussion.content, :class => 'discussion_content updatable_discussion_data plain block', :data => {:discussion_id => @discussion.id}, :placeholder => 'Content' %>
</div>

<div class='add_response_shell'>
  <%= button_to 'add response', discussion_discussions_responses_path(@discussion), :class => 'add_response_btn pure-button', :data => {:discussion_id => @discussion.id} %>
</div>

<div class="discussion_response_shell">
  <% @discussion.discussion_responses.each do |response| %>
    <%= render :partial => 'discussions_responses/indi_show', :locals => {:response => response} %>
  <% end %>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    discussion_id = <%= @discussion.id %>;
    EditProject.init();
  });
</script>

app/views/discussions_responses/_discussion_response_template.html.erb
<div class="create_new_response_shell">
  <%= text_area_tag 'discussion_response[content]', @discussion_response.content, :placeholder => 'Content', :class => 'discussion_response updatable_discussion_response', :data => {:discussion_response_id => @discussion_response.id} %>
  <%= link_to 'Add Response', 'javascript;', :class => 'pure-button update_response_button', :data => {:discussion_response_id => @discussion_response.id } %>
</div>

app/views/discussions_responses/_indi_show.html.erb
<div class="response_shell">
  <p class="responder-name"><%= response.user.first_name %></p>
  <p class="responder-content"><%= response.content %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FiveInch</title>
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.2.1/pure-min.css">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
  <header class="pure-menu pure-menu-open pure-menu-horizontal">
    <ul>
      <li>Org-Yo</li>
      <li><%= link_to 'Home', root_path %></li>
      <% if current_user %>
        <li class="pure-menu-selected"><%= link_to 'Projects', user_path(current_user) %></li>
        <li>Hello <%= current_user.first_name %></li>
        <li><%= link_to 'Signout', signout_path %></li>
      <% else %>
        <li><%= link_to 'Sign Up', signup_path %></li>
        <li><%= link_to 'Log In', login_path %></li>
      <% end %>
    </ul>
  </header>

<%= yield %>

</body>
</html>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= form_for @project, :html => {:class => 'pure-form pure-form-stacked'} do |f| %>
  <%= f.text_field 'name', :placeholder => 'Project Name' %>
  <%= f.submit 'save new project', :class => 'pure-button' %>
<% end %>

app/views/projects/show.html.erb
<%= text_field_tag 'project[name]', @project.name, :class => 'project_title updatable_project_data plain', :data => 
{:project_id => @project.id}, :autocomplete => "off", :placeholder => 'Title' %>
<hr class="line-1">

<h3 class="cat-header">Discussion:</h3>
<%= button_to 'New Discussion', project_discussions_path(@project), :method => :post, :class => 'add_new_discussion_btn pure-button add-discussion-btn', :data => {:project_id => @project.id} %>
<div class="discussion_shell">
  <% @discussions.each do |discussion| %>
    <%= render :partial => 'discussions/discussion_thumb', :locals => {:discussion => discussion} %>
  <% end %>
</div>

<h3 class="cat-header">To-Do's:</h3>

<script type="text/javascript">
  $(document).ready(function(){
    EditProject.init();
  });
</script>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user, :html => {:class => 'pure-form pure-form-stacked'} do |f| %>
  <%= f.text_field 'first_name', :placeholder => 'First Name' %>
  <%= f.text_field 'last_name', :placeholder => 'Last Name' %>
  <%= f.text_field 'email', :placeholder => 'Email' %>
  <%= f.password_field 'password', :placeholder => 'Password' %>

  <%= f.submit 'submit' %>
<% end %>

app/views/users/show.html.erb
<h1>Homepage for <%= @user.first_name %></h1>
<h3>Owned Projects</h3>
<% @owned_projects.each do |project| %>
  <%= link_to project.name, project_path(project) %>
<% end %>

<h3>Joined Projects</h3>
<% @projects.each do |project| %>
  <%= link_to project.name, project_path(project) %>
<% end %>
<%= link_to 'New Project', new_project_path %>

app/views/welcome/index.html.erb
Hello, welcome to the homepage.